name: Deployment Exercise1
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: npm ci
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: npm ci
      - name: test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: npm ci
      - name: Build
        run: npm run build
      - name: Deploy code
        run: echo "Deploying......"
